name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Lint with pylint
        continue-on-error: true
        run: pylint **/*.py

      - name: Vulnerability scan with bandit
        continue-on-error: true
        run: bandit -r .

      - name: Run tests
        run: pytest test_app.py
        env:
          POSTGRES_DB: dummy
          POSTGRES_USER: dummy
          POSTGRES_PASSWORD: dummy
          JWT_KEY: dummy
          APP_PORT: 5001

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt

      - name: Lint with pylint
        continue-on-error: true
        run: pylint **/*.py

      - name: Vulnerability scan with bandit
        continue-on-error: true
        run: bandit -r .

      - name: Run tests
        run: pytest test_app.py
        env:
          SECRET_KEY: dummy

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
